theme: minima
---
title: "Autobiography"
date: 2025-02-09
author: Pedro Serdoura
description: Story of my life in poetry
---
My life has a story
That seems to be normal,
One or another moment of glory
Pointing to a new portal.

I believe and I am convinced
That everyone achievements
Are part of being consisted
And some other elements.

I was born 35 years ago
On the 3rd Sunday of February,
The 3rd son to flow
Coming from the imaginary.

With only 2 years old
I went to pre school
And since then I have been told
That I have a good home rule.
